project:
  type: website
  output-dir: docs

website:
  title: "cindyyupsych.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

publish:
  type: github
  repo: cindyyupsych/cindyyupsych.github.io
